from sympy import *

class SetUpDict:
    def setupdict(self):
        theta, phi, xxx, xxy, xxz, xyx, xyy, xyz, xzx, xzy, xzz, yxx, yxy, yxz, yyx, yyy, yyz, yzx, yzy, yzz, zxx, zxy, zxz, zyx, zyy, zyz, zzx, zzy, zzz, \
        xxxx, xxxy, xxxz, xyxx, xyxy, xyxz, xzxx, xzxy, xzxz, xxyx, xxyy, xxyz, xyyx, xyyy, xyyz, xzyx, xzyy, xzyz, xxzx, xxzy, xxzz, xyzx, xyzy, xyzz, \
        xzzx, xzzy, xzzz, yxxx, yxxy, yxxz, yyxx, yyxy, yyxz, yzxx, yzxy, yzxz, yxyx, yxyy, yxyz, yyyx, yyyy, yyyz, yzyx, yzyy, yzyz, yxzx, yxzy, yxzz, \
        yyzx, yyzy, yyzz, yzzx, yzzy, yzzz, zxxx, zxxy, zxxz, zyxx, zyxy, zyxz, zzxx, zzxy, zzxz, zxyx, zxyy, zxyz, zyyx, zyyy, zyyz, zzyx, zzyy, zzyz, \
        zxzx, zxzy, zxzz, zyzx, zyzy, zyzz, zzzx, zzzy, zzzz = symbols(
        'theta phi xxx xxy xxz xyx xyy xyz xzx xzy xzz yxx yxy yxz yyx yyy yyz yzx yzy yzz zxx zxy zxz zyx zyy zyz zzx '
        'zzy zzz xxxx xxxy xxxz xyxx xyxy xyxz xzxx xzxy xzxz xxyx xxyy xxyz xyyx xyyy xyyz xzyx xzyy xzyz xxzx xxzy '
        'xxzz xyzx xyzy xyzz xzzx xzzy xzzz yxxx yxxy yxxz yyxx yyxy yyxz yzxx yzxy yzxz yxyx yxyy yxyz yyyx yyyy yyyz '
        'yzyx yzyy yzyz yxzx yxzy yxzz yyzx yyzy yyzz yzzx yzzy yzzz zxxx zxxy zxxz zyxx zyxy zyxz zzxx zzxy zzxz zxyx '
        'zxyy zxyz zyyx zyyy zyyz zzyx zzyy zzyz zxzx zxzy zxzz zyzx zyzy zyzz zzzx zzzy zzzz')

        dic = {'Triclinic': {
            'C1': Matrix(
                [[xxx, xyx, xzx], [xxy, xyy, xzy], [xxz, xyz, xzz], [yxx, yyx, yzx], [yxy, yyy, yzy], [yxz, yyz, yzz],
                 [zxx, zyx, zzx], [zxy, zyy, zzy], [zxz, zyz, zzz]]).subs([(xxy, xyx), (xxz, xzx), (xyz, xzy),
                                                                           (yxy, yyx), (yxz, yzx), (yyz, yzy),
                                                                           (zxy, zyx), (zxz, zzx), (zyz, zzy)])},
            'Monoclinic': {'C2': Matrix(
                [[0, xyx, 0], [xxy, 0, xzy], [0, xyz, 0], [yxx, 0, yzx], [0, yyy, 0], [yxz, 0, yzz], [0, zyx, 0],
                 [zxy, 0, zzy], [0, zyz, 0]]).subs([(xxy, xyx), (xyz, xzy), (yxz, yzx), (zxy, zyx), (zyz, zzy)]),
                           'C1h': Matrix(
                               [[xxx, 0, xzx], [0, xyy, 0], [xxz, 0, xzz], [0, yyx, 0], [yxy, 0, yzy], [0, yyz, 0],
                                [zxx, 0, zzx], [0, zyy, 0], [zxz, 0, zzz]]).subs([(xxz, xzx), (yxy, yyx), (yyz, yzy),
                                                                                  (zxz, zzx)])},
            'Orthorhombic': {
                'D2': Matrix([[0, 0, 0], [0, 0, xzy], [0, xyz, 0], [0, 0, yzx], [0, 0, 0], [yxz, 0, 0], [0, zyx, 0],
                              [zxy, 0, 0], [0, 0, 0]]).subs([(xyz, xzy), (yxz, yzx), (zxy, zyx)]),
                'C2v': Matrix(
                    [[0, 0, xzx], [0, 0, 0], [xxz, 0, 0], [0, 0, 0], [0, 0, yzy], [0, yyz, 0], [zxx, 0, 0],
                     [0, zyy, 0], [0, 0, zzz]]).subs([(xxz, xzx), (yyz, yzy)])},
            'Tetragonal': {
                'C4': Matrix([[0, 0, xzx], [0, 0, xzy], [xxz, xyz, 0], [0, 0, yzx], [0, 0, yzy], [yxz, yyz, 0],
                              [zxx, zyx, 0], [zxy, zyy, 0], [0, 0, zzz]]).subs([(xyz, -yxz), (xzy, -yzx), (xzx, yzy),
                                                                                (xxz, yyz), (zxx, zyy), (zxy, -zyx),
                                                                                (yyz, yzy), (yxz, yzx)]),
                'S4': Matrix([[0, 0, xzx], [0, 0, xzy], [xxz, xyz, 0], [0, 0, yzx], [0, 0, yzy], [yxz, yyz, 0],
                              [zxx, zyx, 0], [zxy, zyy, 0], [0, 0, 0]]).subs([(xyz, yxz), (xzy, yzx), (xzx, -yzy),
                                                                              (xxz, -yyz), (zxx, -zyy), (zxy, zyx),
                                                                              (yyz, yzy), (yxz, yzx)]),
                'D4': Matrix([[0, 0, 0], [0, 0, xzy], [0, xyz, 0], [0, 0, yzx], [0, 0, 0], [yxz, 0, 0],
                              [0, zyx, 0], [zxy, 0, 0], [0, 0, 0]]).subs([(xyz, -yxz), (xzy, -yzx), (zxy, -zyx),
                                                                          (yxz, yzx)]),
                'C4v': Matrix([[0, 0, xzx], [0, 0, 0], [xxz, 0, 0], [0, 0, 0], [0, 0, yzy], [0, yyz, 0],
                               [zxx, 0, 0], [0, zyy, 0], [0, 0, zzz]]).subs([(xzx, yzy), (xxz, yyz), (zxx, zyy),
                                                                             (yyz, yzy)]),
                'D2d': Matrix([[0, 0, 0], [0, 0, xzy], [0, xyz, 0], [0, 0, yzx], [0, 0, 0], [yxz, 0, 0],
                               [0, zyx, 0], [zxy, 0, 0], [0, 0, 0]]).subs([(xyz, yxz), (xzy, yzx), (zxy, zyx),
                                                                           (yxz, yzx)])},
            'Trigonal': {'C3': Matrix([[xxx, xyx, xzx],[xxy, xyy, xzy],[xxz, xyz, 0],[yxx, yyx, yzx],[yxy, yyy, yzy],
                                       [yxz, yyz, 0],
                                       [zxx, 0, 0],
                                       [0, zyy, 0],
                                       [0, 0, zzz]]).subs([(xyy, -xxx),
                                                             (yyx, -xxx),
                                                             (yxy, -xxx),
                                                             (xyz, -yxz),
                                                             (xzy, -yzx),
                                                             (xzx, yzy),
                                                             (xxz, yyz),
                                                             (yxx, -yyy),
                                                             (xxy, -yyy),
                                                             (xyx, -yyy),
                                                             (zxx, zyy),
                                                             # (zxy, -zyx), #This term is zero
                                                             (yyz, yzy),
                                                             (yxz, yzx)]),
                'D3': Matrix([[xxx, 0, 0], [0, xyy, xzy], [0, xyz, 0], [0, yyx, yzx], [yxy, 0, 0], [yxz, 0, 0],
                              [0, zyx, 0], [zxy, 0, 0], [0, 0, 0]]).subs(
                    [(xyy, -xxx), (yyx, -xxx), (yxy, -xxx),
                     (xyz, -yxz), (xzy, -yzx), (zxy, -zyx),
                     (yxz, yzx)]),
                'C3v': Matrix(
                    [[0, xyx, xzx], [xxy, 0, 0], [xxz, 0, 0], [yxx, 0, 0], [0, yyy, yzy], [0, yyz, 0],
                     [zxx, 0, 0],
                     [0, zyy, 0], [0, 0, zzz]]).subs(
                    [(xzx, yzy), (xxz, yyz), (zxx, zyy), (yyz, yzy), (yxx, -yyy),
                     (xxy, -yyy), (xyx, -yyy)])},
            'Hexagonal': {
                'C6': Matrix([[0, 0, xzx], [0, 0, xzy], [xxz, xyz, 0], [0, 0, yzx], [0, 0, yzy], [yxz, yyz, 0],
                              [zxx, zyx, 0], [zxy, zyy, 0], [0, 0, zzz]]).subs([(xyz, -yxz), (xzy, -yzx), (xzx, yzy),
                                                                                (xxz, yyz), (zxx, zyy), (zxy, -zyx),
                                                                                (yyz, yzy), (yxz, yzx)]),
                'C3h': Matrix([[xxx, xyx, 0], [xxy, xyy, 0], [0, 0, 0], [yxx, yyx, 0], [yxy, yyy, 0], [0, 0, 0],
                               [0, 0, 0], [0, 0, 0], [0, 0, 0]]).subs([(xyy, -xxx), (yxy, -xxx), (yyx, -xxx),
                                                                       (yxx, -yyy), (xyx, -yyy), (xxy, -yyy)]),
                'D6': Matrix([[0, 0, 0],
                              [0, 0, 0],
                              [0, 0, 0],
                              [0, 0, 0],
                              [0, 0, 0],  # All elements are zero because SHG
                              [0, 0, 0],
                              [0, 0, 0],
                              [0, 0, 0],
                              [0, 0, 0]]),
                'C6v': Matrix([[0, 0, xzx], [0, 0, 0], [xxz, 0, 0], [0, 0, 0], [0, 0, yzy], [0, yyz, 0],
                               [zxx, 0, 0], [0, zyy, 0], [0, 0, zzz]]).subs([(xzx, yzy), (xxz, yyz), (zxx, zyy),
                                                                             (yyz, yzy)]),
                'D3h': Matrix(
                    [[0, xyx, 0], [xxy, 0, 0], [0, 0, 0], [yxx, 0, 0], [0, yyy, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
                     [0, 0, 0]]).subs([(yxx, -yyy), (xxy, -yyy), (xyx, -yyy)])},
            'Cubic': {'O': Matrix([[0, 0, 0], [0, 0, xzy], [0, xyz, 0], [0, 0, yzx], [0, 0, 0], [yxz, 0, 0],
                                   [0, zyx, 0], [zxy, 0, 0], [0, 0, 0]]).subs([(xzy, -xyz), (yzx, xyz), (yxz, -xyz),(zxy, xyz), (zyx, -xyz)]),
                      'Td': Matrix([[0, 0, 0], [0, 0, xzy], [0, xyz, 0], [0, 0, yzx], [0, 0, 0], [yxz, 0, 0],
                                    [0, zyx, 0], [zxy, 0, 0], [0, 0, 0]]).subs([(xzy, xyz), (yzx, xyz), (yxz, xyz),(zxy, xyz), (zyx, xyz)]),
                      'T': Matrix([[0, 0, 0], [0, 0, xzy], [0, xyz, 0], [0, 0, yzx], [0, 0, 0], [yxz, 0, 0],
                                   [0, zyx, 0], [zxy, 0, 0], [0, 0, 0]]).subs([(yzx, xyz), (zxy, xyz), (yxz, xzy),(zyx, xzy), (xyz, xzy)])}
        }

        dic_qud = {
            'Triclinic': {'C1': Matrix([[xxxx, xxxy, xxxz, xyxx, xyxy, xyxz, xzxx, xzxy, xzxz],
                                        [xxyx, xxyy, xxyz, xyyx, xyyy, xyyz, xzyx, xzyy, xzyz],
                                        [xxzx, xxzy, xxzz, xyzx, xyzy, xyzz, xzzx, xzzy, xzzz],
                                        [yxxx, yxxy, yxxz, yyxx, yyxy, yyxz, yzxx, yzxy, yzxz],
                                        [yxyx, yxyy, yxyz, yyyx, yyyy, yyyz, yzyx, yzyy, yzyz],
                                        [yxzx, yxzy, yxzz, yyzx, yyzy, yyzz, yzzx, yzzy, yzzz],
                                        [zxxx, zxxy, zxxz, zyxx, zyxy, zyxz, zzxx, zzxy, zzxz],
                                        [zxyx, zxyy, zxyz, zyyx, zyyy, zyyz, zzyx, zzyy, zzyz],
                                        [zxzx, zxzy, zxzz, zyzx, zyzy, zyzz, zzzx, zzzy, zzzz]]).subs([(xxxy, xyxx),
                                                                                                       (xxyy, xyyx),
                                                                                                       (xxzy, xyzx),
                                                                                                       (yxxy, yyxx),
                                                                                                       (yxyy, yyyx),
                                                                                                       (yxzy, yyzx),
                                                                                                       (zxxy, zyxx),
                                                                                                       (zxyy, zyyx),
                                                                                                       (zxzy, zyzx),
                                                                                                       (xxxz, xzxx),
                                                                                                       (xxyz, xzyx),
                                                                                                       (xxzz, xzzx),
                                                                                                       (yxxz, yzxx),
                                                                                                       (yxyz, yzyx),
                                                                                                       (yxzz, yzzx),
                                                                                                       (zxxz, zzxx),
                                                                                                       (zxyz, zzyx),
                                                                                                       (zxzz, zzzx),
                                                                                                       (xyxz, xzxy),
                                                                                                       (xyyz, xzyy),
                                                                                                       (xyzz, xzzy),
                                                                                                       (yyxz, yzxy),
                                                                                                       (yyyz, yzyy),
                                                                                                       (yyzz, yzzy),
                                                                                                       (zyxz, zzxy),
                                                                                                       (zyyz, zzyy),
                                                                                                       (zyzz, zzzy)]),
                          'S2': Matrix([[xxxx, xxxy, xxxz, xyxx, xyxy, xyxz, xzxx, xzxy, xzxz],
                                        [xxyx, xxyy, xxyz, xyyx, xyyy, xyyz, xzyx, xzyy, xzyz],
                                        [xxzx, xxzy, xxzz, xyzx, xyzy, xyzz, xzzx, xzzy, xzzz],
                                        [yxxx, yxxy, yxxz, yyxx, yyxy, yyxz, yzxx, yzxy, yzxz],
                                        [yxyx, yxyy, yxyz, yyyx, yyyy, yyyz, yzyx, yzyy, yzyz],
                                        [yxzx, yxzy, yxzz, yyzx, yyzy, yyzz, yzzx, yzzy, yzzz],
                                        [zxxx, zxxy, zxxz, zyxx, zyxy, zyxz, zzxx, zzxy, zzxz],
                                        [zxyx, zxyy, zxyz, zyyx, zyyy, zyyz, zzyx, zzyy, zzyz],
                                        [zxzx, zxzy, zxzz, zyzx, zyzy, zyzz, zzzx, zzzy, zzzz]]).subs(
                              [(xxxy, xyxx),
                               (xxyy, xyyx),
                               (xxzy, xyzx),
                               (yxxy, yyxx),
                               (yxyy, yyyx),
                               (yxzy, yyzx),
                               (zxxy, zyxx),
                               (zxyy, zyyx),
                               (zxzy, zyzx),
                               (xxxz, xzxx),
                               (xxyz, xzyx),
                               (xxzz, xzzx),
                               (yxxz, yzxx),
                               (yxyz, yzyx),
                               (yxzz, yzzx),
                               (zxxz, zzxx),
                               (zxyz, zzyx),
                               (zxzz, zzzx),
                               (xyxz, xzxy),
                               (xyyz, xzyy),
                               (xyzz, xzzy),
                               (yyxz, yzxy),
                               (yyyz, yzyy),
                               (yyzz, yzzy),
                               (zyxz, zzxy),
                               (zyyz, zzyy),
                               (zyzz, zzzy)])
                          },

        'Monoclinic': {'C2': Matrix([[xxxx, 0, xxxz, 0, xyxy, 0, xzxx, 0, xzxz],
                                     [0, xxyy, 0, xyyx, 0, xyyz, 0, xzyy, 0],
                                     [xxzx, 0, xxzz, 0, xyzy, 0, xzzx, 0, xzzz],
                                     [0, yxxy, 0, yyxx, 0, yyxz, 0, yzxy, 0],
                                     [yxyx, 0, yxyz, 0, yyyy, 0, yzyx, 0, yzyz],
                                     [0, yxzy, 0, yyzx, 0, yyzz, 0, yzzy, 0],
                                     [zxxx, 0, zxxz, 0, zyxy, 0, zzxx, 0, zzxz],
                                     [0, zxyy, 0, zyyx, 0, zyyz, 0, zzyy, 0],
                                     [zxzx, 0, zxzz, 0, zyzy, 0, zzzx, 0, zzzz]]).subs([(xxyy, xyyx),
                                                                                        (yxxy, yyxx),
                                                                                        (yxzy, yyzx),
                                                                                        (zxyy, zyyx),
                                                                                        (xxxz, xzxx),
                                                                                        (xxzz, xzzx),
                                                                                        (yxyz, yzyx),
                                                                                        (zxxz, zzxx),
                                                                                        (zxzz, zzzx),
                                                                                        (xyyz, xzyy),
                                                                                        (yyxz, yzxy),
                                                                                        (yyzz, yzzy),
                                                                                        (zyyz, zzyy)]),

                       'C1h': Matrix([[xxxx, 0, xxxz, 0, xyxy, 0, xzxx, 0, xzxz],
                                      [0, xxyy, 0, xyyx, 0, xyyz, 0, xzyy, 0],
                                      [xxzx, 0, xxzz, 0, xyzy, 0, xzzx, 0, xzzz],
                                      [0, yxxy, 0, yyxx, 0, yyxz, 0, yzxy, 0],
                                      [yxyx, 0, yxyz, 0, yyyy, 0, yzyx, 0, yzyz],
                                      [0, yxzy, 0, yyzx, 0, yyzz, 0, yzzy, 0],
                                      [zxxx, 0, zxxz, 0, zyxy, 0, zzxx, 0, zzxz],
                                      [0, zxyy, 0, zyyx, 0, zyyz, 0, zzyy, 0],
                                      [zxzx, 0, zxzz, 0, zyzy, 0, zzzx, 0, zzzz]]).subs([(xxyy, xyyx),
                                                                                         (yxxy, yyxx),
                                                                                         (yxzy, yyzx),
                                                                                         (zxyy, zyyx),
                                                                                         (xxxz, xzxx),
                                                                                         (xxzz, xzzx),
                                                                                         (yxyz, yzyx),
                                                                                         (zxxz, zzxx),
                                                                                         (zxzz, zzzx),
                                                                                         (xyyz, xzyy),
                                                                                         (yyxz, yzxy),
                                                                                         (yyzz, yzzy),
                                                                                         (zyyz, zzyy)]),
                       'C2h': Matrix([[xxxx, 0, xxxz, 0, xyxy, 0, xzxx, 0, xzxz],
                                      [0, xxyy, 0, xyyx, 0, xyyz, 0, xzyy, 0],
                                      [xxzx, 0, xxzz, 0, xyzy, 0, xzzx, 0, xzzz],  # Before rotation
                                      [0, yxxy, 0, yyxx, 0, yyxz, 0, yzxy, 0],
                                      [yxyx, 0, yxyz, 0, yyyy, 0, yzyx, 0, yzyz],
                                      [0, yxzy, 0, yyzx, 0, yyzz, 0, yzzy, 0],
                                      [zxxx, 0, zxxz, 0, zyxy, 0, zzxx, 0, zzxz],
                                      [0, zxyy, 0, zyyx, 0, zyyz, 0, zzyy, 0],
                                      [zxzx, 0, zxzz, 0, zyzy, 0, zzzx, 0, zzzz]]).subs([(xxyy, xyyx),
                                                                                         (yxxy, yyxx),
                                                                                         (yxzy, yyzx),
                                                                                         (zxyy, zyyx),
                                                                                         (xxxz, xzxx),
                                                                                         (xxzz, xzzx),
                                                                                         (yxyz, yzyx),
                                                                                         (zxxz, zzxx),
                                                                                         (zxzz, zzzx),
                                                                                         (xyyz, xzyy),
                                                                                         (yyxz, yzxy),
                                                                                         (yyzz, yzzy),
                                                                                         (zyyz, zzyy)])
                       },
            'Orthorhombic': {'D2': Matrix([[xxxx, 0, 0, 0, xyxy, 0, 0, 0, xzxz],
                                           [0, xxyy, 0, xyyx, 0, 0, 0, 0, 0],
                                           [0, 0, xxzz, 0, 0, 0, xzzx, 0, 0],
                                           [0, yxxy, 0, yyxx, 0, 0, 0, 0, 0],
                                           [yxyx, 0, 0, 0, yyyy, 0, 0, 0, yzyz],
                                           [0, 0, 0, 0, 0, yyzz, 0, yzzy, 0],
                                           [0, 0, zxxz, 0, 0, 0, zzxx, 0, 0],
                                           [0, 0, 0, 0, 0, zyyz, 0, zzyy, 0],
                                           [zxzx, 0, 0, 0, zyzy, 0, 0, 0, zzzz]]).subs([(xxyy, xyyx),
                                                                                        (yxxy, yyxx),
                                                                                        (xxzz, xzzx),
                                                                                        (zxxz, zzxx),
                                                                                        (yyzz, yzzy),
                                                                                        (zyyz, zzyy)]),

                             'C2v': Matrix([[xxxx, 0, 0, 0, xyxy, 0, 0, 0, xzxz],
                                            [0, xxyy, 0, xyyx, 0, 0, 0, 0, 0],
                                            [0, 0, xxzz, 0, 0, 0, xzzx, 0, 0],
                                            [0, yxxy, 0, yyxx, 0, 0, 0, 0, 0],
                                            [yxyx, 0, 0, 0, yyyy, 0, 0, 0, yzyz],
                                            [0, 0, 0, 0, 0, yyzz, 0, yzzy, 0],
                                            [0, 0, zxxz, 0, 0, 0, zzxx, 0, 0],
                                            [0, 0, 0, 0, 0, zyyz, 0, zzyy, 0],
                                            [zxzx, 0, 0, 0, zyzy, 0, 0, 0, zzzz]]).subs([(xxyy, xyyx),
                                                                                         (yxxy, yyxx),
                                                                                         (xxzz, xzzx),
                                                                                         (zxxz, zzxx),
                                                                                         (yyzz, yzzy),
                                                                                         (zyyz, zzyy)]),

                             'D2h': Matrix([[xxxx, 0, 0, 0, xyxy, 0, 0, 0, xzxz],
                                            [0, xxyy, 0, xyyx, 0, 0, 0, 0, 0],
                                            [0, 0, xxzz, 0, 0, 0, xzzx, 0, 0],
                                            [0, yxxy, 0, yyxx, 0, 0, 0, 0, 0],
                                            [yxyx, 0, 0, 0, yyyy, 0, 0, 0, yzyz],
                                            [0, 0, 0, 0, 0, yyzz, 0, yzzy, 0],
                                            [0, 0, zxxz, 0, 0, 0, zzxx, 0, 0],
                                            [0, 0, 0, 0, 0, zyyz, 0, zzyy, 0],
                                            [zxzx, 0, 0, 0, zyzy, 0, 0, 0, zzzz]]).subs([(xxyy, xyyx),
                                                                                         (yxxy, yyxx),
                                                                                         (xxzz, xzzx),
                                                                                         (zxxz, zzxx),
                                                                                         (yyzz, yzzy),
                                                                                         (zyyz, zzyy)])
                             },
            'Tetragonal': {
                'C4': Matrix([
                    [xxxx, xxxy, 0, xyxx, xyxy, 0, 0, 0, xzxz],
                    [xxyx, xxyy, 0, xyyx, xyyy, 0, 0, 0, xzyz],
                    [0, 0, xxzz, 0, 0, xyzz, xzzx, xzzy, 0],
                    [yxxx, yxxy, 0, yyxx, yyxy, 0, 0, 0, yzxz],
                    [yxyx, yxyy, 0, yyyx, yyyy, 0, 0, 0, yzyz],
                    [0, 0, yxzz, 0, 0, yyzz, yzzx, yzzy, 0],
                    [0, 0, zxxz, 0, 0, zyxz, zzxx, zzxy, 0],
                    [0, 0, zxyz, 0, 0, zyyz, zzyx, zzyy, 0],
                    [zxzx, zxzy, 0, zyzx, zyzy, 0, 0, 0, zzzz]])

                .subs(
                    [(xxxx, yyyy),
                     (zzxx, zzyy),
                     (zxxz, zzyy),
                     (zyyz, zzyy),
                     (xxzz, yyzz),
                     (xzzx, yyzz),
                     (yzzy, yyzz),
                     (zxzx, zyzy),
                     (xzxz, yzyz),
                     (xyzz, -yxzz),
                     (xzzy, -yxzz),
                     (yzzx, yxzz),
                     (zzxy, -zzyx),
                     (zxyz, -zzyx),
                     (zyxz, zzyx),
                     (xzyz, -yzxz),
                     (zxzy, -zyzx),
                     (xxyy, yyxx),
                     (xyyx, yyxx),
                     (yxxy, yyxx),
                     (xyxy, yxyx),
                     (xxxy, -yyyx),
                     (xyxx, -yyyx),
                     (yxyy, yyyx),
                     (xxyx, -yyxy),
                     (yxxx, -xyyy)]),
                'S4': Matrix([
                    [xxxx, xxxy, 0, xyxx, xyxy, 0, 0, 0, xzxz],
                    [xxyx, xxyy, 0, xyyx, xyyy, 0, 0, 0, xzyz],
                    [0, 0, xxzz, 0, 0, xyzz, xzzx, xzzy, 0],
                    [yxxx, yxxy, 0, yyxx, yyxy, 0, 0, 0, yzxz],
                    [yxyx, yxyy, 0, yyyx, yyyy, 0, 0, 0, yzyz],
                    [0, 0, yxzz, 0, 0, yyzz, yzzx, yzzy, 0],
                    [0, 0, zxxz, 0, 0, zyxz, zzxx, zzxy, 0],
                    [0, 0, zxyz, 0, 0, zyyz, zzyx, zzyy, 0],
                    [zxzx, zxzy, 0, zyzx, zyzy, 0, 0, 0, zzzz]])

                .subs(
                    [(xxxx, yyyy),
                     (zzxx, zzyy),
                     (zxxz, zzyy),
                     (zyyz, zzyy),
                     (xxzz, yyzz),
                     (xzzx, yyzz),
                     (yzzy, yyzz),
                     (zxzx, zyzy),
                     (xzxz, yzyz),
                     (xyzz, -yxzz),
                     (xzzy, -yxzz),
                     (yzzx, yxzz),
                     (zzxy, -zzyx),
                     (zxyz, -zzyx),
                     (zyxz, zzyx),
                     (xzyz, -yzxz),
                     (zxzy, -zyzx),
                     (xxyy, yyxx),
                     (xyyx, yyxx),
                     (yxxy, yyxx),
                     (xyxy, yxyx),
                     (xxxy, -yyyx),
                     (xyxx, -yyyx),
                     (yxyy, yyyx),
                     (xxyx, -yyxy),
                     (yxxx, -xyyy)]),
                'C4h': Matrix([
                    [xxxx, xxxy, 0, xyxx, xyxy, 0, 0, 0, xzxz],
                    [xxyx, xxyy, 0, xyyx, xyyy, 0, 0, 0, xzyz],
                    [0, 0, xxzz, 0, 0, xyzz, xzzx, xzzy, 0],
                    [yxxx, yxxy, 0, yyxx, yyxy, 0, 0, 0, yzxz],
                    [yxyx, yxyy, 0, yyyx, yyyy, 0, 0, 0, yzyz],
                    [0, 0, yxzz, 0, 0, yyzz, yzzx, yzzy, 0],
                    [0, 0, zxxz, 0, 0, zyxz, zzxx, zzxy, 0],
                    [0, 0, zxyz, 0, 0, zyyz, zzyx, zzyy, 0],
                    [zxzx, zxzy, 0, zyzx, zyzy, 0, 0, 0, zzzz]])

                .subs(
                    [(xxxx, yyyy),
                     (zzxx, zzyy),
                     (zxxz, zzyy),
                     (zyyz, zzyy),
                     (xxzz, yyzz),
                     (xzzx, yyzz),
                     (yzzy, yyzz),
                     (zxzx, zyzy),
                     (xzxz, yzyz),
                     (xyzz, -yxzz),
                     (xzzy, -yxzz),
                     (yzzx, yxzz),
                     (zzxy, -zzyx),
                     (zxyz, -zzyx),
                     (zyxz, zzyx),
                     (xzyz, -yzxz),
                     (zxzy, -zyzx),
                     (xxyy, yyxx),
                     (xyyx, yyxx),
                     (yxxy, yyxx),
                     (xyxy, yxyx),
                     (xxxy, -yyyx),
                     (xyxx, -yyyx),
                     (yxyy, yyyx),
                     (xxyx, -yyxy),
                     (yxxx, -xyyy)]),
                'D4': Matrix([[xxxx, 0, 0, 0, xyxy, 0, 0, 0, xzxz],
                              [0, xxyy, 0, xyyx, 0, 0, 0, 0, 0],
                              [0, 0, xxzz, 0, 0, 0, xzzx, 0, 0],
                              [0, yxxy, 0, yyxx, 0, 0, 0, 0, 0],
                              [yxyx, 0, 0, 0, yyyy, 0, 0, 0, yzyz],
                              [0, 0, 0, 0, 0, yyzz, 0, yzzy, 0],
                              [0, 0, zxxz, 0, 0, 0, zzxx, 0, 0],
                              [0, 0, 0, 0, 0, zyyz, 0, zzyy, 0],
                              [zxzx, 0, 0, 0, zyzy, 0, 0, 0, zzzz]]).subs([(xxxx, yyyy),
                                                                           (yyzz, xxzz),
                                                                           (yzzy, xxzz),
                                                                           (xzzx, xxzz),
                                                                           (xxyy, yyxx),
                                                                           (xyyx, yyxx),
                                                                           (yxxy, yyxx),
                                                                           (zzyy, zzxx),
                                                                           (zyyz, zzxx),
                                                                           (zxxz, zzxx),
                                                                           (yzyz, xzxz),
                                                                           (xyxy, yxyx),
                                                                           (zyzy, zxzx)]),

                'C4v': Matrix([[xxxx, 0, 0, 0, xyxy, 0, 0, 0, xzxz],
                               [0, xxyy, 0, xyyx, 0, 0, 0, 0, 0],
                               [0, 0, xxzz, 0, 0, 0, xzzx, 0, 0],
                               [0, yxxy, 0, yyxx, 0, 0, 0, 0, 0],
                               [yxyx, 0, 0, 0, yyyy, 0, 0, 0, yzyz],
                               [0, 0, 0, 0, 0, yyzz, 0, yzzy, 0],
                               [0, 0, zxxz, 0, 0, 0, zzxx, 0, 0],
                               [0, 0, 0, 0, 0, zyyz, 0, zzyy, 0],
                               [zxzx, 0, 0, 0, zyzy, 0, 0, 0, zzzz]]).subs([(xxxx, yyyy),
                                                                            (yyzz, xxzz),
                                                                            (yzzy, xxzz),
                                                                            (xzzx, xxzz),
                                                                            (xxyy, yyxx),
                                                                            (xyyx, yyxx),
                                                                            (yxxy, yyxx),
                                                                            (zzyy, zzxx),
                                                                            (zyyz, zzxx),
                                                                            (zxxz, zzxx),
                                                                            (yzyz, xzxz),
                                                                            (xyxy, yxyx),
                                                                            (zyzy, zxzx)]),

                'D4h': Matrix([[xxxx, 0, 0, 0, xyxy, 0, 0, 0, xzxz],
                               [0, xxyy, 0, xyyx, 0, 0, 0, 0, 0],
                               [0, 0, xxzz, 0, 0, 0, xzzx, 0, 0],
                               [0, yxxy, 0, yyxx, 0, 0, 0, 0, 0],
                               [yxyx, 0, 0, 0, yyyy, 0, 0, 0, yzyz],
                               [0, 0, 0, 0, 0, yyzz, 0, yzzy, 0],
                               [0, 0, zxxz, 0, 0, 0, zzxx, 0, 0],
                               [0, 0, 0, 0, 0, zyyz, 0, zzyy, 0],
                               [zxzx, 0, 0, 0, zyzy, 0, 0, 0, zzzz]]).subs([(xxxx, yyyy),
                                                                            (yyzz, xxzz),
                                                                            (yzzy, xxzz),
                                                                            (xzzx, xxzz),
                                                                            (xxyy, yyxx),
                                                                            (xyyx, yyxx),
                                                                            (yxxy, yyxx),
                                                                            (zzyy, zzxx),
                                                                            (zyyz, zzxx),
                                                                            (zxxz, zzxx),
                                                                            (yzyz, xzxz),
                                                                            (xyxy, yxyx),
                                                                            (zyzy, zxzx)]),

                'D2d': Matrix([[xxxx, 0, 0, 0, xyxy, 0, 0, 0, xzxz],
                               [0, xxyy, 0, xyyx, 0, 0, 0, 0, 0],
                               [0, 0, xxzz, 0, 0, 0, xzzx, 0, 0],
                               [0, yxxy, 0, yyxx, 0, 0, 0, 0, 0],
                               [yxyx, 0, 0, 0, yyyy, 0, 0, 0, yzyz],
                               [0, 0, 0, 0, 0, yyzz, 0, yzzy, 0],
                               [0, 0, zxxz, 0, 0, 0, zzxx, 0, 0],
                               [0, 0, 0, 0, 0, zyyz, 0, zzyy, 0],
                               [zxzx, 0, 0, 0, zyzy, 0, 0, 0, zzzz]]).subs([(xxxx, yyyy),
                                                                            (yyzz, xxzz),
                                                                            (yzzy, xxzz),
                                                                            (xzzx, xxzz),
                                                                            (xxyy, yyxx),
                                                                            (xyyx, yyxx),
                                                                            (yxxy, yyxx),
                                                                            (zzyy, zzxx),
                                                                            (zyyz, zzxx),
                                                                            (zxxz, zzxx),
                                                                            (yzyz, xzxz),
                                                                            (xyxy, yxyx),
                                                                            (zyzy, zxzx)])
            },

            'Trigonal': {'C3': Matrix([[xxxx, xxxy, xxxz, xyxx, xyxy, xyxz, xzxx, xzxy, xzxz],
                                       [xxyx, xxyy, xxyz, xyyx, xyyy, xyyz, xzyx, xzyy, xzyz],
                                       [xxzx, xxzy, xxzz, xyzx, xyzy, xyzz, xzzx, xzzy, 0],
                                       [yxxx, yxxy, yxxz, yyxx, yyxy, yyxz, yzxx, yzxy, yzxz],
                                       [yxyx, yxyy, yxyz, yyyx, yyyy, yyyz, yzyx, yzyy, yzyz],
                                       [yxzx, yxzy, yxzz, yyzx, yyzy, yyzz, yzzx, yzzy, 0],
                                       [zxxx, zxxy, zxxz, zyxx, zyxy, zyxz, zzxx, zzxy, 0],
                                       [zxyx, zxyy, zxyz, zyyx, zyyy, zyyz, zzyx, zzyy, 0],
                                       [zxzx, 0, 0, 0, zyzy, 0, 0, 0, zzzz]]).subs(
                [(xxyy, yyxx),
                 (xyyx, yyxx),
                 (yxxy, yyxx),
                 (xyxy, yxyx),
                 (yyzz, xxzz),
                 (yzzy, xxzz),
                 (xzzx, xxzz),
                 (zzyy, zzxx),
                 (zyyz, zzxx),
                 (zxxz, zzxx),
                 (yzyz, xzxz),
                 (zyzy, zxzx),
                 (xyzz, -yxzz),
                 (xzzy, -yxzz),
                 (yzzx, yxzz),
                 (zzxy, -zzyx),
                 (zxyz, -zzyx),
                 (zyxz, zzyx),
                 (xzyz, -yzxz),
                 # (zxzy, -zyzx), These are 0
                 (yyxy, -xxyx),
                 (yxyy, -xyxx),
                 (xyyy, -yxxx),
                 (xxyz, -yyyz),
                 (xyxz, -yyyz),
                 (yxxz, -yyyz),
                 (xzxy, -yyyz),
                 (xzyx, -yyyz),
                 (yzxx, -yyyz),
                 (yzyy, yyyz),
                 (xxzy, -yyzy),
                 (xyzx, -yyzy),
                 (yxzx, -yyzy),
                 (xxxy, -xxyx - xyxx - yxxx),
                 (yyyx, xxyx + xyxx + yxxx),
                 (zxxy, -zyyy),
                 (zxyx, -zyyy),
                 (zyxx, -zyyy),
                 (yyxz, -xxxz),
                 (yxyz, -xxxz),
                 (xyyz, -xxxz),
                 (xzyy, -xxxz),
                 (yzyx, -xxxz),
                 (yzxy, -xxxz),
                 (xzxx, xxxz),
                 (yyzx, -xxzx),
                 (yxzy, -xxzx),
                 (xyzy, -xxzx),
                 (zyyx, -zxxx),
                 (zyxy, -zxxx),
                 (zxyy, -zxxx),
                 (xxxx, yyxx + yyxx + yxyx),
                 (yyyy, yyxx + yyxx + yxyx)]),

                'S6': Matrix([[xxxx, xxxy, xxxz, xyxx, xyxy, xyxz, xzxx, xzxy, xzxz],
                              [xxyx, xxyy, xxyz, xyyx, xyyy, xyyz, xzyx, xzyy, xzyz],
                              [xxzx, xxzy, xxzz, xyzx, xyzy, xyzz, xzzx, xzzy, 0],
                              [yxxx, yxxy, yxxz, yyxx, yyxy, yyxz, yzxx, yzxy, yzxz],
                              [yxyx, yxyy, yxyz, yyyx, yyyy, yyyz, yzyx, yzyy, yzyz],
                              [yxzx, yxzy, yxzz, yyzx, yyzy, yyzz, yzzx, yzzy, 0],
                              [zxxx, zxxy, zxxz, zyxx, zyxy, zyxz, zzxx, zzxy, 0],
                              [zxyx, zxyy, zxyz, zyyx, zyyy, zyyz, zzyx, zzyy, 0],
                              [zxzx, 0, 0, 0, zyzy, 0, 0, 0, zzzz]]).subs(
                    [(xxyy, yyxx),
                     (xyyx, yyxx),
                     (yxxy, yyxx),
                     (xyxy, yxyx),
                     (yyzz, xxzz),
                     (yzzy, xxzz),
                     (xzzx, xxzz),
                     (zzyy, zzxx),
                     (zyyz, zzxx),
                     (zxxz, zzxx),
                     (yzyz, xzxz),
                     (zyzy, zxzx),
                     (xyzz, -yxzz),
                     (xzzy, -yxzz),
                     (yzzx, yxzz),
                     (zzxy, -zzyx),
                     (zxyz, -zzyx),
                     (zyxz, zzyx),
                     (xzyz, -yzxz),
                     # (zxzy, -zyzx), These are 0
                     (yyxy, -xxyx),
                     (yxyy, -xyxx),
                     (xyyy, -yxxx),
                     (xxyz, -yyyz),
                     (xyxz, -yyyz),
                     (yxxz, -yyyz),
                     (xzxy, -yyyz),
                     (xzyx, -yyyz),
                     (yzxx, -yyyz),
                     (yzyy, yyyz),
                     (xxzy, -yyzy),
                     (xyzx, -yyzy),
                     (yxzx, -yyzy),
                     (xxxy, -xxyx - xyxx - yxxx),
                     (yyyx, xxyx + xyxx + yxxx),
                     (zxxy, -zyyy),
                     (zxyx, -zyyy),
                     (zyxx, -zyyy),
                     (yyxz, -xxxz),
                     (yxyz, -xxxz),
                     (xyyz, -xxxz),
                     (xzyy, -xxxz),
                     (yzyx, -xxxz),
                     (yzxy, -xxxz),
                     (xzxx, xxxz),
                     (yyzx, -xxzx),
                     (yxzy, -xxzx),
                     (xyzy, -xxzx),
                     (zyyx, -zxxx),
                     (zyxy, -zxxx),
                     (zxyy, -zxxx),
                     (xxxx, yyxx + yyxx + yxyx),
                     (yyyy, yyxx + yyxx + yxyx)]),

                'C3v': Matrix([[xxxx, 0, xxxz, 0, xyxy, 0, xzxx, 0, xzxz],
                               [0, xxyy, 0, xyyx, 0, xyyz, 0, xzyy, 0],
                               [xxzx, 0, xxzz, 0, xyzy, 0, xzzx, 0, 0],
                               [0, yxxy, 0, yyxx, 0, yyxz, 0, yzxy, 0],
                               [yxyx, 0, yxyz, 0, yyyy, 0, yzyx, 0, yzyz],
                               [0, yxzy, 0, yyzx, 0, yyzz, 0, yzzy, 0],
                               [zxxx, 0, zxxz, 0, zyxy, 0, zzxx, 0, 0],
                               [0, zxyy, 0, zyyx, 0, zyyz, 0, zzyy, 0],
                               [zxzx, 0, 0, 0, zyzy, 0, 0, 0, zzzz]]).subs(
                    [(xxyy, yyxx),
                     (xyyx, yyxx),
                     (yxxy, yyxx),
                     (xyxy, yxyx),
                     (yyzz, xxzz),
                     (xzzx, xxzz),
                     (yzzy, xxzz),
                     (zzyy, zzxx),
                     (zxxz, zzxx),
                     (zyyz, zzxx),
                     (yyxz, -xxxz),
                     (yxyz, -xxxz),
                     (xyyz, -xxxz),
                     (yyzx, -xxzx),
                     (yxzy, -xxzx),
                     (xyzy, -xxzx),
                     (yzyx, -xxxz),
                     (yzxy, -xxxz),
                     (xzyy, -xxxz),
                     (xzxx, xxxz),
                     (zyyx, -zxxx),
                     (zyxy, -zxxx),
                     (zxyy, -zxxx),
                     (yzyz, xzxz),
                     (zyzy, zxzx),
                     (xxxx, yyxx + yyxx + yxyx),
                     (yyyy, yyxx + yyxx + yxyx)]),

                'D3d': Matrix([[xxxx, 0, xxxz, 0, xyxy, 0, xzxx, 0, xzxz],
                               [0, xxyy, 0, xyyx, 0, xyyz, 0, xzyy, 0],
                               [xxzx, 0, xxzz, 0, xyzy, 0, xzzx, 0, 0],
                               [0, yxxy, 0, yyxx, 0, yyxz, 0, yzxy, 0],
                               [yxyx, 0, yxyz, 0, yyyy, 0, yzyx, 0, yzyz],
                               [0, yxzy, 0, yyzx, 0, yyzz, 0, yzzy, 0],
                               [zxxx, 0, zxxz, 0, zyxy, 0, zzxx, 0, 0],
                               [0, zxyy, 0, zyyx, 0, zyyz, 0, zzyy, 0],
                               [zxzx, 0, 0, 0, zyzy, 0, 0, 0, zzzz]]).subs(
                    [(xxyy, yyxx),
                     (xyyx, yyxx),
                     (yxxy, yyxx),
                     (xyxy, yxyx),
                     (yyzz, xxzz),
                     (xzzx, xxzz),
                     (yzzy, xxzz),
                     (zzyy, zzxx),
                     (zxxz, zzxx),
                     (zyyz, zzxx),
                     (yyxz, -xxxz),
                     (yxyz, -xxxz),
                     (xyyz, -xxxz),
                     (yyzx, -xxzx),
                     (yxzy, -xxzx),
                     (xyzy, -xxzx),
                     (yzyx, -xxxz),
                     (yzxy, -xxxz),
                     (xzyy, -xxxz),
                     (xzxx, xxxz),
                     (zyyx, -zxxx),
                     (zyxy, -zxxx),
                     (zxyy, -zxxx),
                     (yzyz, xzxz),
                     (zyzy, zxzx),
                     (xxxx, yyxx + yyxx + yxyx),
                     (yyyy, yyxx + yyxx + yxyx)]),

                'D3': Matrix([[xxxx, 0, xxxz, 0, xyxy, 0, xzxx, 0, xzxz],
                              [0, xxyy, 0, xyyx, 0, xyyz, 0, xzyy, 0],
                              [xxzx, 0, xxzz, 0, xyzy, 0, xzzx, 0, 0],
                              [0, yxxy, 0, yyxx, 0, yyxz, 0, yzxy, 0],
                              [yxyx, 0, yxyz, 0, yyyy, 0, yzyx, 0, yzyz],
                              [0, yxzy, 0, yyzx, 0, yyzz, 0, yzzy, 0],
                              [zxxx, 0, zxxz, 0, zyxy, 0, zzxx, 0, 0],
                              [0, zxyy, 0, zyyx, 0, zyyz, 0, zzyy, 0],
                              [zxzx, 0, 0, 0, zyzy, 0, 0, 0, zzzz]]).subs(
                    [(xxyy, yyxx),
                     (xyyx, yyxx),
                     (yxxy, yyxx),
                     (xyxy, yxyx),
                     (yyzz, xxzz),
                     (xzzx, xxzz),
                     (yzzy, xxzz),
                     (zzyy, zzxx),
                     (zxxz, zzxx),
                     (zyyz, zzxx),
                     (yyxz, -xxxz),
                     (yxyz, -xxxz),
                     (xyyz, -xxxz),
                     (yyzx, -xxzx),
                     (yxzy, -xxzx),
                     (xyzy, -xxzx),
                     (yzyx, -xxxz),
                     (yzxy, -xxxz),
                     (xzyy, -xxxz),
                     (xzxx, xxxz),
                     (zyyx, -zxxx),
                     (zyxy, -zxxx),
                     (zxyy, -zxxx),
                     (yzyz, xzxz),
                     (zyzy, zxzx),
                     (xxxx, yyxx + yyxx + yxyx),
                     (yyyy, yyxx + yyxx + yxyx)])
            },


            'Hexagonal': {'C6': Matrix([[xxxx, xxxy, 0, xyxx, xyxy, 0, 0, 0, xzxz],  # After
                                        [xxyx, xxyy, 0, xyyx, xyyy, 0, 0, 0, xzyz],
                                        [0, 0, xxzz, 0, 0, xyzz, xzzx, xzzy, 0],
                                        [yxxx, yxxy, 0, yyxx, yyxy, 0, 0, 0, yzxz],
                                        [yxyx, yxyy, 0, yyyx, yyyy, 0, 0, 0, yzyz],
                                        [0, 0, yxzz, 0, 0, yyzz, yzzx, yzzy, 0],
                                        [0, 0, zxxz, 0, 0, zyxz, zzxx, zzxy, 0],
                                        [0, 0, zxyz, 0, 0, zyyz, zzyx, zzyy, 0],
                                        [zxzx, zxzy, 0, zyzx, zyzy, 0, 0, 0, zzzz]]).subs(
                [(xxyy, yyxx),
                 (xyyx, yyxx),
                 (yxxy, yyxx),
                 (xyxy, yxyx),
                 (xxxx, yyxx + yyxx + yxyx),
                 (yyyy, yyxx + yyxx + yxyx),
                 (yyzz, xxzz),
                 (yzzy, xxzz),
                 (xzzx, xxzz),
                 (zzyy, zzxx),
                 (zyyz, zzxx),
                 (zxxz, zzxx),
                 (yzyz, xzxz),
                 (zyzy, zxzx),
                 (xyzz, -yxzz),
                 (xzzy, -yxzz),
                 (yzzx, yxzz),
                 (zzxy, -zzyx),
                 (zxyz, -zzyx),
                 (zyxz, zzyx),
                 (xzyz, -yzxz),
                 (zxzy, -zyzx),
                 (yyxy, -xxyx),
                 (yxyy, -xyxx),
                 (xyyy, -yxxx),
                 (xxxy, - xxyx - xyxx - yxxx),
                 (yyyx, xxyx + xyxx + yxxx)]),
                'C3h': Matrix([[xxxx, xxxy, 0, xyxx, xyxy, 0, 0, 0, xzxz],  # After
                               [xxyx, xxyy, 0, xyyx, xyyy, 0, 0, 0, xzyz],
                               [0, 0, xxzz, 0, 0, xyzz, xzzx, xzzy, 0],
                               [yxxx, yxxy, 0, yyxx, yyxy, 0, 0, 0, yzxz],
                               [yxyx, yxyy, 0, yyyx, yyyy, 0, 0, 0, yzyz],
                               [0, 0, yxzz, 0, 0, yyzz, yzzx, yzzy, 0],
                               [0, 0, zxxz, 0, 0, zyxz, zzxx, zzxy, 0],
                               [0, 0, zxyz, 0, 0, zyyz, zzyx, zzyy, 0],
                               [zxzx, zxzy, 0, zyzx, zyzy, 0, 0, 0, zzzz]]).subs(
                    [(xxyy, yyxx),
                     (xyyx, yyxx),
                     (yxxy, yyxx),
                     (xyxy, yxyx),
                     (xxxx, yyxx + yyxx + yxyx),
                     (yyyy, yyxx + yyxx + yxyx),
                     (yyzz, xxzz),
                     (yzzy, xxzz),
                     (xzzx, xxzz),
                     (zzyy, zzxx),
                     (zyyz, zzxx),
                     (zxxz, zzxx),
                     (yzyz, xzxz),
                     (zyzy, zxzx),
                     (xyzz, -yxzz),
                     (xzzy, -yxzz),
                     (yzzx, yxzz),
                     (zzxy, -zzyx),
                     (zxyz, -zzyx),
                     (zyxz, zzyx),
                     (xzyz, -yzxz),
                     (zxzy, -zyzx),
                     (yyxy, -xxyx),
                     (yxyy, -xyxx),
                     (xyyy, -yxxx),
                     (xxxy, - xxyx - xyxx - yxxx),
                     (yyyx, xxyx + xyxx + yxxx)]),
                'C6h': Matrix([[xxxx, xxxy, 0, xyxx, xyxy, 0, 0, 0, xzxz],  # After
                               [xxyx, xxyy, 0, xyyx, xyyy, 0, 0, 0, xzyz],
                               [0, 0, xxzz, 0, 0, xyzz, xzzx, xzzy, 0],
                               [yxxx, yxxy, 0, yyxx, yyxy, 0, 0, 0, yzxz],
                               [yxyx, yxyy, 0, yyyx, yyyy, 0, 0, 0, yzyz],
                               [0, 0, yxzz, 0, 0, yyzz, yzzx, yzzy, 0],
                               [0, 0, zxxz, 0, 0, zyxz, zzxx, zzxy, 0],
                               [0, 0, zxyz, 0, 0, zyyz, zzyx, zzyy, 0],
                               [zxzx, zxzy, 0, zyzx, zyzy, 0, 0, 0, zzzz]]).subs(
                    [(xxyy, yyxx),
                     (xyyx, yyxx),
                     (yxxy, yyxx),
                     (xyxy, yxyx),
                     (xxxx, yyxx + yyxx + yxyx),
                     (yyyy, yyxx + yyxx + yxyx),
                     (yyzz, xxzz),
                     (yzzy, xxzz),
                     (xzzx, xxzz),
                     (zzyy, zzxx),
                     (zyyz, zzxx),
                     (zxxz, zzxx),
                     (yzyz, xzxz),
                     (zyzy, zxzx),
                     (xyzz, -yxzz),
                     (xzzy, -yxzz),
                     (yzzx, yxzz),
                     (zzxy, -zzyx),
                     (zxyz, -zzyx),
                     (zyxz, zzyx),
                     (xzyz, -yzxz),
                     (zxzy, -zyzx),
                     (yyxy, -xxyx),
                     (yxyy, -xyxx),
                     (xyyy, -yxxx),
                     (xxxy, - xxyx - xyxx - yxxx),
                     (yyyx, xxyx + xyxx + yxxx)]),
                'D6': Matrix([[xxxx, 0, 0, 0, xyxy, 0, 0, 0, xzxz],
                              [0, xxyy, 0, xyyx, 0, 0, 0, 0, 0],
                              [0, 0, xxzz, 0, 0, 0, xzzx, 0, 0],
                              [0, yxxy, 0, yyxx, 0, 0, 0, 0, 0],
                              [yxyx, 0, 0, 0, yyyy, 0, 0, 0, yzyz],
                              [0, 0, 0, 0, 0, yyzz, 0, yzzy, 0],
                              [0, 0, zxxz, 0, 0, 0, zzxx, 0, 0],
                              [0, 0, 0, 0, 0, zyyz, 0, zzyy, 0],
                              [zxzx, 0, 0, 0, zyzy, 0, 0, 0, zzzz]]).subs(
                    [(xxyy, yyxx),
                     (xyyx, yyxx),
                     (yxxy, yyxx),
                     (xyxy, yxyx),
                     (yyzz, xxzz),
                     (yzzy, xxzz),
                     (xzzx, xxzz),
                     (zzyy, zzxx),
                     (zyyz, zzxx),
                     (zxxz, zzxx),
                     (yzyz, xzxz),
                     (zyzy, zxzx),
                     (xxxx, yyxx + yyxx + yxyx),
                     (yyyy, yyxx + yyxx + yxyx)]),
                'C6v': Matrix([[xxxx, 0, 0, 0, xyxy, 0, 0, 0, xzxz],
                               [0, xxyy, 0, xyyx, 0, 0, 0, 0, 0],
                               [0, 0, xxzz, 0, 0, 0, xzzx, 0, 0],
                               [0, yxxy, 0, yyxx, 0, 0, 0, 0, 0],
                               [yxyx, 0, 0, 0, yyyy, 0, 0, 0, yzyz],
                               [0, 0, 0, 0, 0, yyzz, 0, yzzy, 0],
                               [0, 0, zxxz, 0, 0, 0, zzxx, 0, 0],
                               [0, 0, 0, 0, 0, zyyz, 0, zzyy, 0],
                               [zxzx, 0, 0, 0, zyzy, 0, 0, 0, zzzz]]).subs(
                    [(xxyy, yyxx),
                     (xyyx, yyxx),
                     (yxxy, yyxx),
                     (xyxy, yxyx),
                     (yyzz, xxzz),
                     (yzzy, xxzz),
                     (xzzx, xxzz),
                     (zzyy, zzxx),
                     (zyyz, zzxx),
                     (zxxz, zzxx),
                     (yzyz, xzxz),
                     (zyzy, zxzx),
                     (xxxx, yyxx + yyxx + yxyx),
                     (yyyy, yyxx + yyxx + yxyx)]),
                'D6h': Matrix([[xxxx, 0, 0, 0, xyxy, 0, 0, 0, xzxz],
                               [0, xxyy, 0, xyyx, 0, 0, 0, 0, 0],
                               [0, 0, xxzz, 0, 0, 0, xzzx, 0, 0],
                               [0, yxxy, 0, yyxx, 0, 0, 0, 0, 0],
                               [yxyx, 0, 0, 0, yyyy, 0, 0, 0, yzyz],
                               [0, 0, 0, 0, 0, yyzz, 0, yzzy, 0],
                               [0, 0, zxxz, 0, 0, 0, zzxx, 0, 0],
                               [0, 0, 0, 0, 0, zyyz, 0, zzyy, 0],
                               [zxzx, 0, 0, 0, zyzy, 0, 0, 0, zzzz]]).subs(
                    [(xxyy, yyxx),
                     (xyyx, yyxx),
                     (yxxy, yyxx),
                     (xyxy, yxyx),
                     (yyzz, xxzz),
                     (yzzy, xxzz),
                     (xzzx, xxzz),
                     (zzyy, zzxx),
                     (zyyz, zzxx),
                     (zxxz, zzxx),
                     (yzyz, xzxz),
                     (zyzy, zxzx),
                     (xxxx, yyxx + yyxx + yxyx),
                     (yyyy, yyxx + yyxx + yxyx)]),
                'D3h': Matrix([[xxxx, 0, 0, 0, xyxy, 0, 0, 0, xzxz],
                               [0, xxyy, 0, xyyx, 0, 0, 0, 0, 0],
                               [0, 0, xxzz, 0, 0, 0, xzzx, 0, 0],
                               [0, yxxy, 0, yyxx, 0, 0, 0, 0, 0],
                               [yxyx, 0, 0, 0, yyyy, 0, 0, 0, yzyz],
                               [0, 0, 0, 0, 0, yyzz, 0, yzzy, 0],
                               [0, 0, zxxz, 0, 0, 0, zzxx, 0, 0],
                               [0, 0, 0, 0, 0, zyyz, 0, zzyy, 0],
                               [zxzx, 0, 0, 0, zyzy, 0, 0, 0, zzzz]]).subs(
                    [(xxyy, yyxx),
                     (xyyx, yyxx),
                     (yxxy, yyxx),
                     (xyxy, yxyx),
                     (yyzz, xxzz),
                     (yzzy, xxzz),
                     (xzzx, xxzz),
                     (zzyy, zzxx),
                     (zyyz, zzxx),
                     (zxxz, zzxx),
                     (yzyz, xzxz),
                     (zyzy, zxzx),
                     (xxxx, yyxx + yyxx + yxyx),
                     (yyyy, yyxx + yyxx + yxyx)])
            },

            'Cubic': {'Th': Matrix([[xxxx, 0, 0, 0, xyxy, 0, 0, 0, xzxz],
                                    [0, xxyy, 0, xyyx, 0, 0, 0, 0, 0],
                                    [0, 0, xxzz, 0, 0, 0, xzzx, 0, 0],
                                    [0, yxxy, 0, yyxx, 0, 0, 0, 0, 0],
                                    [yxyx, 0, 0, 0, yyyy, 0, 0, 0, yzyz],
                                    [0, 0, 0, 0, 0, yyzz, 0, yzzy, 0],
                                    [0, 0, zxxz, 0, 0, 0, zzxx, 0, 0],
                                    [0, 0, 0, 0, 0, zyyz, 0, zzyy, 0],
                                    [zxzx, 0, 0, 0, zyzy, 0, 0, 0, zzzz]]).subs([(zzzz, xxxx),
                                                                                 (yyyy, xxxx),
                                                                                 (xxyy, yyzz),
                                                                                 (zzxx, yyzz),
                                                                                 (yyxx, zzyy),
                                                                                 (xxzz, zzyy),
                                                                                 (xyxy, yzyz),
                                                                                 (zxzx, yzyz),
                                                                                 (yxyx, zyzy),
                                                                                 (xzxz, zyzy),
                                                                                 (xyyx, yzzy),
                                                                                 (zxxz, yzzy),
                                                                                 (yxxy, zyyz),
                                                                                 (xzzx, zyyz),
                                                                                 (yyzz, yzzy),
                                                                                 (zyyz, zzyy)]),
                      'T': Matrix([[xxxx, 0, 0, 0, xyxy, 0, 0, 0, xzxz],
                                   [0, xxyy, 0, xyyx, 0, 0, 0, 0, 0],
                                   [0, 0, xxzz, 0, 0, 0, xzzx, 0, 0],
                                   [0, yxxy, 0, yyxx, 0, 0, 0, 0, 0],
                                   [yxyx, 0, 0, 0, yyyy, 0, 0, 0, yzyz],
                                   [0, 0, 0, 0, 0, yyzz, 0, yzzy, 0],
                                   [0, 0, zxxz, 0, 0, 0, zzxx, 0, 0],
                                   [0, 0, 0, 0, 0, zyyz, 0, zzyy, 0],
                                   [zxzx, 0, 0, 0, zyzy, 0, 0, 0, zzzz]]).subs([(zzzz, xxxx),
                                                                                (yyyy, xxxx),
                                                                                (xxyy, yyzz),
                                                                                (zzxx, yyzz),
                                                                                (yyxx, zzyy),
                                                                                (xxzz, zzyy),
                                                                                (xyxy, yzyz),
                                                                                (zxzx, yzyz),
                                                                                (yxyx, zyzy),
                                                                                (xzxz, zyzy),
                                                                                (xyyx, yzzy),
                                                                                (zxxz, yzzy),
                                                                                (yxxy, zyyz),
                                                                                (xzzx, zyyz),
                                                                                (yyzz, yzzy),
                                                                                (zyyz, zzyy)]),
                      'O': Matrix([[xxxx, 0, 0, 0, xyxy, 0, 0, 0, xzxz],
                                   [0, xxyy, 0, xyyx, 0, 0, 0, 0, 0],
                                   [0, 0, xxzz, 0, 0, 0, xzzx, 0, 0],
                                   [0, yxxy, 0, yyxx, 0, 0, 0, 0, 0],
                                   [yxyx, 0, 0, 0, yyyy, 0, 0, 0, yzyz],
                                   [0, 0, 0, 0, 0, yyzz, 0, yzzy, 0],
                                   [0, 0, zxxz, 0, 0, 0, zzxx, 0, 0],
                                   [0, 0, 0, 0, 0, zyyz, 0, zzyy, 0],
                                   [zxzx, 0, 0, 0, zyzy, 0, 0, 0, zzzz]]).subs([(zzzz, xxxx),
                                                                                (yyyy, xxxx),
                                                                                (zzyy, yyzz),
                                                                                (zzxx, yyzz),
                                                                                (xxzz, yyzz),
                                                                                (xxyy, yyzz),
                                                                                (yyxx, yyzz),
                                                                                (zyzy, yzyz),
                                                                                (zxzx, yzyz),
                                                                                (xzxz, yzyz),
                                                                                (xyxy, yzyz),
                                                                                (yxyx, yzyz),
                                                                                (zyyz, yzzy),
                                                                                (zxxz, yzzy),
                                                                                (xzzx, yzzy),
                                                                                (xyyx, yzzy),
                                                                                (yxxy, yzzy),
                                                                                (yyzz, yzzy)]),
                      'Td': Matrix([[xxxx, 0, 0, 0, xyxy, 0, 0, 0, xzxz],
                                    [0, xxyy, 0, xyyx, 0, 0, 0, 0, 0],
                                    [0, 0, xxzz, 0, 0, 0, xzzx, 0, 0],
                                    [0, yxxy, 0, yyxx, 0, 0, 0, 0, 0],
                                    [yxyx, 0, 0, 0, yyyy, 0, 0, 0, yzyz],
                                    [0, 0, 0, 0, 0, yyzz, 0, yzzy, 0],
                                    [0, 0, zxxz, 0, 0, 0, zzxx, 0, 0],
                                    [0, 0, 0, 0, 0, zyyz, 0, zzyy, 0],
                                    [zxzx, 0, 0, 0, zyzy, 0, 0, 0, zzzz]]).subs([(zzzz, xxxx),
                                                                                 (yyyy, xxxx),
                                                                                 (zzyy, yyzz),
                                                                                 (zzxx, yyzz),
                                                                                 (xxzz, yyzz),
                                                                                 (xxyy, yyzz),
                                                                                 (yyxx, yyzz),
                                                                                 (zyzy, yzyz),
                                                                                 (zxzx, yzyz),
                                                                                 (xzxz, yzyz),
                                                                                 (xyxy, yzyz),
                                                                                 (yxyx, yzyz),
                                                                                 (zyyz, yzzy),
                                                                                 (zxxz, yzzy),
                                                                                 (xzzx, yzzy),
                                                                                 (xyyx, yzzy),
                                                                                 (yxxy, yzzy),
                                                                                 (yyzz, yzzy)]),
                      'Oh': Matrix([[xxxx, 0, 0, 0, xyxy, 0, 0, 0, xzxz],
                                    [0, xxyy, 0, xyyx, 0, 0, 0, 0, 0],
                                    [0, 0, xxzz, 0, 0, 0, xzzx, 0, 0],
                                    [0, yxxy, 0, yyxx, 0, 0, 0, 0, 0],
                                    [yxyx, 0, 0, 0, yyyy, 0, 0, 0, yzyz],
                                    [0, 0, 0, 0, 0, yyzz, 0, yzzy, 0],
                                    [0, 0, zxxz, 0, 0, 0, zzxx, 0, 0],
                                    [0, 0, 0, 0, 0, zyyz, 0, zzyy, 0],
                                    [zxzx, 0, 0, 0, zyzy, 0, 0, 0, zzzz]]).subs([(zzzz, xxxx),
                                                                                 (yyyy, xxxx),
                                                                                 (zzyy, yyzz),
                                                                                 (zzxx, yyzz),
                                                                                 (xxzz, yyzz),
                                                                                 (xxyy, yyzz),
                                                                                 (yyxx, yyzz),
                                                                                 (zyzy, yzyz),
                                                                                 (zxzx, yzyz),
                                                                                 (xzxz, yzyz),
                                                                                 (xyxy, yzyz),
                                                                                 (yxyx, yzyz),
                                                                                 (zyyz, yzzy),
                                                                                 (zxxz, yzzy),
                                                                                 (xzzx, yzzy),
                                                                                 (xyyx, yzzy),
                                                                                 (yxxy, yzzy),
                                                                                 (yyzz, yzzy)]),

                      }
        }

        dic_mag_dip = {
            'Triclinic': {
                'C1': Matrix(
                    [[xxx, xyx, xzx], [xxy, xyy, xzy], [xxz, xyz, xzz], [yxx, yyx, yzx], [yxy, yyy, yzy],
                     [yxz, yyz, yzz],
                     [zxx, zyx, zzx], [zxy, zyy, zzy], [zxz, zyz, zzz]]).subs([(xyx, xxy), (xzx, xxz), (xzy, xyz),
                                                                               (yyx, yxy), (yzx, yxz), (yzy, yyz),
                                                                               (zyx, zxy), (zzx, zxz), (zzy, zyz)]),
                'S2': Matrix(
                    [[xxx, xyx, xzx], [xxy, xyy, xzy], [xxz, xyz, xzz], [yxx, yyx, yzx], [yxy, yyy, yzy],
                     [yxz, yyz, yzz],
                     [zxx, zyx, zzx], [zxy, zyy, zzy], [zxz, zyz, zzz]]).subs([(xyx, xxy), (xzx, xxz), (xzy, xyz),
                                                                               (yyx, yxy), (yzx, yxz), (yzy, yyz),
                                                                               (zyx, zxy), (zzx, zxz), (zzy, zyz)])
            },

            'Monoclinic': {
                'C2': Matrix(
                    [[0, xyx, 0], [xxy, 0, xzy], [0, xyz, 0], [yxx, 0, yzx], [0, yyy, 0], [yxz, 0, yzz], [0, zyx, 0],
                     [zxy, 0, zzy], [0, zyz, 0]]).subs([(xyx, xxy), (xzy, xyz), (yzx, yxz), (zyx, zxy), (zzy, zyz)]),

                'C1h': Matrix(
                    [[0, xyx, 0], [xxy, 0, xzy], [0, xyz, 0], [yxx, 0, yzx], [0, yyy, 0], [yxz, 0, yzz], [0, zyx, 0],
                     [zxy, 0, zzy], [0, zyz, 0]]).subs([(xyx, xxy), (xzy, xyz), (yzx, yxz), (zyx, zxy), (zzy, zyz)]),

                'C2h': Matrix(
                    [[0, xyx, 0], [xxy, 0, xzy], [0, xyz, 0], [yxx, 0, yzx], [0, yyy, 0], [yxz, 0, yzz], [0, zyx, 0],
                     [zxy, 0, zzy], [0, zyz, 0]]).subs([(xyx, xxy), (xzy, xyz), (yzx, yxz), (zyx, zxy), (zzy, zyz)])
            },

            'Orthorhombic': {
                'D2': Matrix([[0, 0, 0], [0, 0, xzy], [0, xyz, 0], [0, 0, yzx], [0, 0, 0], [yxz, 0, 0], [0, zyx, 0],
                              [zxy, 0, 0], [0, 0, 0]]).subs([(xzy, xyz), (yzx, yxz), (zyx, zxy)]),

                'C2v': Matrix([[0, 0, 0], [0, 0, xzy], [0, xyz, 0], [0, 0, yzx], [0, 0, 0], [yxz, 0, 0], [0, zyx, 0],
                               [zxy, 0, 0], [0, 0, 0]]).subs([(xzy, xyz), (yzx, yxz), (zyx, zxy)]),

                'D2h': Matrix([[0, 0, 0], [0, 0, xzy], [0, xyz, 0], [0, 0, yzx], [0, 0, 0], [yxz, 0, 0], [0, zyx, 0],
                               [zxy, 0, 0], [0, 0, 0]]).subs([(xzy, xyz), (yzx, yxz), (zyx, zxy)])
            },

            'Tetragonal': {
                'C4': Matrix([[0, 0, xzx], [0, 0, xzy], [xxz, xyz, 0], [0, 0, yzx], [0, 0, yzy], [yxz, yyz, 0],
                              [zxx, 0, 0], [0, zyy, 0], [0, 0, zzz]]).subs([(xzx, xxz), (yzy, xxz), (yyz, xxz),
                                                                            (xzy, xyz), (yxz, -xyz), (yzx, -xyz),
                                                                            (zyy, zxx)]),

                'S4': Matrix([[0, 0, xzx], [0, 0, xzy], [xxz, xyz, 0], [0, 0, yzx], [0, 0, yzy], [yxz, yyz, 0],
                              [zxx, 0, 0], [0, zyy, 0], [0, 0, zzz]]).subs([(xzx, xxz), (yzy, xxz), (yyz, xxz),
                                                                            (xzy, xyz), (yxz, -xyz), (yzx, -xyz),
                                                                            (zyy, zxx)]),

                'D4': Matrix([[0, 0, 0], [0, 0, xzy], [0, xyz, 0], [0, 0, yzx], [0, 0, 0], [yxz, 0, 0],
                              [0, 0, 0], [0, 0, 0], [0, 0, 0]]).subs([(xzy, xyz), (yxz, -xyz), (yzx, -xyz)]),

                'C4v': Matrix([[0, 0, 0], [0, 0, xzy], [0, xyz, 0], [0, 0, yzx], [0, 0, 0], [yxz, 0, 0],
                               [0, 0, 0], [0, 0, 0], [0, 0, 0]]).subs([(xzy, xyz), (yxz, -xyz), (yzx, -xyz)]),

                'D2d': Matrix([[0, 0, 0], [0, 0, xzy], [0, xyz, 0], [0, 0, yzx], [0, 0, 0], [yxz, 0, 0],
                               [0, 0, 0], [0, 0, 0], [0, 0, 0]]).subs([(xzy, xyz), (yxz, -xyz), (yzx, -xyz)]),

                'C4h': Matrix([[0, 0, xzx], [0, 0, xzy], [xxz, xyz, 0], [0, 0, yzx], [0, 0, yzy], [yxz, yyz, 0],
                               [zxx, 0, 0], [0, zyy, 0], [0, 0, zzz]]).subs([(xzx, xxz), (yzy, xxz), (yyz, xxz),
                                                                             (xzy, xyz), (yxz, -xyz), (yzx, -xyz),
                                                                             (zyy, zxx)]),

                'D4h': Matrix([[0, 0, 0], [0, 0, xzy], [0, xyz, 0], [0, 0, yzx], [0, 0, 0], [yxz, 0, 0],
                               [0, 0, 0], [0, 0, 0], [0, 0, 0]]).subs([(xzy, xyz), (yxz, -xyz), (yzx, -xyz)])
            },

            'Trigonal': {
                'C3': Matrix([[xxx, xyx, xzx], [xxy, xyy, xzy], [xxz, xyz, 0], [yxx, yyx, yzx], [yxy, yyy, yzy],
                              [yxz, yyz, 0], [zxx, 0, 0], [0, zyy, 0], [0, 0, zzz]]).subs(
                    [(xyy, -xxx), (yxy, -xxx), (yyx, -xxx),
                     (xyx, xxy), (yxx, xxy), (yyy, -xxy),
                     (xzx, xxz), (yyz, xxz), (yzy, xxz),
                     (xzy, xyz), (yxz, -xyz), (yzx, -xyz),
                     (zyy, zxx)]),

                'D3': Matrix([[xxx, 0, 0], [0, xyy, xzy], [0, xyz, 0], [0, yyx, yzx], [yxy, 0, 0], [yxz, 0, 0],
                              [0, 0, 0], [0, 0, 0], [0, 0, 0]]).subs(
                    [(xyy, -xxx), (yxy, -xxx), (yyx, -xxx),
                     (xzy, xyz), (yxz, -xyz), (yzx, -xyz)]),

                'C3v': Matrix([[xxx, 0, 0], [0, xyy, xzy], [0, xyz, 0], [0, yyx, yzx], [yxy, 0, 0], [yxz, 0, 0],
                               [0, 0, 0], [0, 0, 0], [0, 0, 0]]).subs(
                    [(xyy, -xxx), (yxy, -xxx), (yyx, -xxx),
                     (xzy, xyz), (yxz, -xyz), (yzx, -xyz)]),

                'S6': Matrix([[xxx, xyx, xzx], [xxy, xyy, xzy], [xxz, xyz, 0], [yxx, yyx, yzx], [yxy, yyy, yzy],
                              [yxz, yyz, 0], [zxx, 0, 0], [0, zyy, 0], [0, 0, zzz]]).subs(
                    [(xyy, -xxx), (yxy, -xxx), (yyx, -xxx),
                     (xyx, xxy), (yxx, xxy), (yyy, -xxy),
                     (xzx, xxz), (yyz, xxz), (yzy, xxz),
                     (xzy, xyz), (yxz, -xyz), (yzx, -xyz),
                     (zyy, zxx)]),

                'D3d': Matrix([[xxx, 0, 0], [0, xyy, xzy], [0, xyz, 0], [0, yyx, yzx], [yxy, 0, 0], [yxz, 0, 0],
                               [0, 0, 0], [0, 0, 0], [0, 0, 0]]).subs(
                    [(xyy, -xxx), (yxy, -xxx), (yyx, -xxx),
                     (xzy, xyz), (yxz, -xyz), (yzx, -xyz)])

            },

            'Hexagonal': {
                'C6': Matrix([[0, 0, xzx], [0, 0, xzy], [xxz, xyz, 0], [0, 0, yzx], [0, 0, yzy], [yxz, yyz, 0],
                              [zxx, 0, 0], [0, zyy, 0], [0, 0, zzz]]).subs([(xzx, xxz), (yzy, xxz), (yyz, xxz),
                                                                            (xzy, xyz), (yxz, -xyz), (yzx, -xyz),
                                                                            (zyy, zxx)]),
                'C3h': Matrix([[0, 0, xzx], [0, 0, xzy], [xxz, xyz, 0], [0, 0, yzx], [0, 0, yzy], [yxz, yyz, 0],
                               [zxx, 0, 0], [0, zyy, 0], [0, 0, zzz]]).subs([(xzx, xxz), (yzy, xxz), (yyz, xxz),
                                                                             (xzy, xyz), (yxz, -xyz), (yzx, -xyz),
                                                                             (zyy, zxx)]),
                'D6': Matrix([[0, 0, 0], [0, 0, xzy], [0, xyz, 0], [0, 0, yzx], [0, 0, 0], [yxz, 0, 0],
                              [0, 0, 0], [0, 0, 0], [0, 0, 0]]).subs([(xzy, xyz), (yxz, -xyz), (yzx, -xyz)]),
                'C6v': Matrix([[0, 0, 0], [0, 0, xzy], [0, xyz, 0], [0, 0, yzx], [0, 0, 0], [yxz, 0, 0],
                               [0, 0, 0], [0, 0, 0], [0, 0, 0]]).subs([(xzy, xyz), (yxz, -xyz), (yzx, -xyz)]),
                'D3h': Matrix([[0, 0, 0], [0, 0, xzy], [0, xyz, 0], [0, 0, yzx], [0, 0, 0], [yxz, 0, 0],
                               [0, 0, 0], [0, 0, 0], [0, 0, 0]]).subs([(xzy, xyz), (yxz, -xyz), (yzx, -xyz)]),
                'C6h': Matrix([[0, 0, xzx], [0, 0, xzy], [xxz, xyz, 0], [0, 0, yzx], [0, 0, yzy], [yxz, yyz, 0],
                               [zxx, 0, 0], [0, zyy, 0], [0, 0, zzz]]).subs([(xzx, xxz), (yzy, xxz), (yyz, xxz),
                                                                             (xzy, xyz), (yxz, -xyz), (yzx, -xyz),
                                                                             (zyy, zxx)]),
                'D6h': Matrix([[0, 0, 0], [0, 0, xzy], [0, xyz, 0], [0, 0, yzx], [0, 0, 0], [yxz, 0, 0],
                               [0, 0, 0], [0, 0, 0], [0, 0, 0]]).subs([(xzy, xyz), (yxz, -xyz), (yzx, -xyz)])
            },

            'Cubic': {
                'O': Matrix([[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
                             [0, 0, 0]]),

                'Td': Matrix([[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
                              [0, 0, 0]]),

                'T': Matrix([[0, 0, 0], [0, 0, xzy], [0, xyz, 0], [0, 0, yzx], [0, 0, 0], [yxz, 0, 0],
                             [0, zyx, 0], [zxy, 0, 0], [0, 0, 0]]).subs([(yzx, xyz), (zxy, xyz), (yxz, xyz),
                                                                         (zyx, xyz), (xzy, xyz)]),

                'Th': Matrix([[0, 0, 0], [0, 0, xzy], [0, xyz, 0], [0, 0, yzx], [0, 0, 0], [yxz, 0, 0],
                              [0, zyx, 0], [zxy, 0, 0], [0, 0, 0]]).subs([(yzx, xyz), (zxy, xyz), (yxz, xyz),
                                                                          (zyx, xyz), (xzy, xyz)]),

                'Oh': Matrix([[0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0],
                              [0, 0, 0]])
            }
        }
        return dic, dic_qud, dic_mag_dip